name: hermine-ci
on: workflow_dispatch
jobs: 
  hermine: 
    name: hermine
    runs-on: ubuntu-latest
    steps:
      - run: curl https://chantier.hermine-foss.org/api/upload_spdx/ -X POST -F 'spdx_file=@venom_short.spdx.yaml' -F 'release_id=24'
    
