name: hermine-ci
on:
  - push
  - workflow_dispatch
jobs: 
  hermine: 
    name: hermine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "curl  -H 'Authorization: Token=${{ secrets.TOKEN }}' https://chantier.hermine-foss.org/api/upload_spdx/ -X PUT -F 'spdx_file=@venom_short.spdx.yaml' -F 'release_id=24'"
