name: hermine-ci
on: workflow_dispatch
jobs: 
  hermine: 
    name: hermine
    runs-on: ubuntu-latest
    steps:
      - working-directory: ./.github/workflows
        run: pwd 
      - name: where am i
        working-directory: ./.github/workflows
        run: ls -a
      - working-directory: ./.github/workflows
        run: curl https://chantier.hermine-foss.org/api/upload_spdx/ -X PUT -F 'spdx_file=@venom_short.spdx.yaml' -F 'release_id=24'
    
