name: hermine-ci
on:
  - push
  - workflow_dispatch
jobs:
  validation-steps:
    runs-on: ubuntu-latest
    steps:
      - name: validation-1
        id: validation-1
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/33/unnormalised_usages'
          method: 'GET'
          # bearerToken: 
      - name: Show Response
        run: echo ${{ steps.validation-1.outputs.response }}
      
      - name: validation-2
        id: validation-2
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/33/licenses_to_check'
          method: 'GET'
          # bearerToken: 
      - name: Show Response
        run: echo ${{ steps.validation-2.outputs.response }}
      
      - name: validation-3
        id: validation-3
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/33/licenses_usages'
          method: 'GET'
          # bearerToken: 
      - name: Show Response
        run: echo ${{ steps.validation-3.outputs.response }}
      
      - name: validation-4
        id: validation-4
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/33/licenses_against_policy'
          method: 'GET'
          # bearerToken: 
      - name: Show Response
        run: echo ${{ steps.validation-4.outputs.response }}
