name: validation-steps
on:
  workflow_dispatch:
    inputs:
      release_id:
        type: string
        description: ID of the release to run the validation on
        required: true

jobs:
  validation-1:
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: call
        id: call
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/${{github.event.inputs.release_id}}/unnormalised_usages'
          method: 'GET'
          # bearerToken: 
      - id: set-result
        run: echo "::set-output name=result::${{ steps.call.outputs.response }}"
        
        
  validation-2:
    needs: validation-1
    if: fromJSON(needs.validation-1.outputs.result).valid
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: call
        id: call
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/${{github.event.inputs.release_id}}/licenses_to_check'
          method: 'GET'
          # bearerToken: 
      - id: set-result
        run: echo "::set-output name=result::${{ steps.call.outputs.response }}"

        
  validation-3:
    needs: validation-2
    if: fromJSON(needs.validation-2.outputs.result).valid
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: call
        id: call
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/${{github.event.inputs.release_id}}/licenses_usages'
          method: 'GET'
          # bearerToken: 
      - id: set-result
        run: echo "::set-output name=result::${{ steps.call.outputs.response }}"
  
  validation-4:
    needs: validation-3
    if: fromJSON(needs.validation-3.outputs.result).valid
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: call
        id: call
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/${{github.event.inputs.release_id}}/licenses_against_policy'
          method: 'GET'
          # bearerToken: 
      - id: set-result
        run: echo "::set-output name=result::${{ steps.call.outputs.response }}"
        
  success:
     needs: validation-4
     if: fromJSON(needs.validation-4.outputs.result).valid
     runs-on: ubuntu-latest
     steps:
        - id: success
          run: echo "The release ${{github.event.inputs.release_id}} is good to go !"
