name: hermine-ci
on:
  - push
  - workflow_dispatch
jobs:
  validation-1:
    runs-on: ubuntu-latest
    steps:
      - name: API call
        id: validation-1
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chantier.hermine-foss.org/api/releases/33/unnormalised_usages'
          method: 'GET'
          # bearerToken: 
          # username: ${{ secrets.AWX_USER }}
          # password: ${{ secrets.AWX_PASSWORD }}
      - name: Show Response
        run: echo ${{ steps.validation-1.outputs.response }}
